const main=document.querySelector('main'), dialog=document.querySelector('#cinema'), toastEl=document.querySelector('#toast')
const storageKey='ciberdojo-cinematic-proposal-v1'
let bank, items, state={belt:0,mentor:'doggoteka',progress:{},exams:{}},toastTimer
try{const saved=JSON.parse(localStorage.getItem(storageKey));if(saved&&Number.isInteger(saved.belt)&&saved.belt>=0&&saved.belt<7&&saved.progress&&saved.exams)state={...state,...saved}}catch{}
const colors=['#eee9d5','#dbb94b','#cf834c','#839b67','#659bac','#ac8966','#3c4541']
const labels=['Blanco','Amarillo','Naranja','Verde','Azul','Marrón','Negro']
const mentorNames={doggoteka:'DoggoTeka',sensei:'Sensei Ren',kira:'Kira',aria:'Aria'}
if(!mentorNames[state.mentor])state.mentor='sensei'
const icon=(name)=>{const paths={arrow:'<path d="M4 10h12m-5-5 5 5-5 5"/>',shield:'<path d="M10 2 3 5v5c0 4 7 8 7 8s7-4 7-8V5Z"/><path d="m6 10 3 3 5-6"/>',book:'<path d="M10 5v13M10 5C6 2 2 3 2 3v13s4-1 8 2c4-3 8-2 8-2V3s-4-1-8 2Z"/>',clock:'<circle cx="10" cy="10" r="8"/><path d="M10 5v5l3 2"/>',lock:'<rect x="4" y="9" width="12" height="9" rx="1"/><path d="M6 9V6a4 4 0 0 1 8 0v3"/>'};return `<svg viewBox="0 0 20 20" aria-hidden="true">${paths[name]||paths.arrow}</svg>`}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const current=()=>bank.dojos[state.belt]
function progress(d){if(!state.progress[d.id])state.progress[d.id]={answers:[],cursor:0};return state.progress[d.id]}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));return true}catch{toast('El navegador no permite guardar. Mantén esta pestaña abierta para continuar.');return false}}
function toast(text){clearTimeout(toastTimer);toastEl.textContent=text;toastEl.classList.add('show');toastTimer=setTimeout(()=>toastEl.classList.remove('show'),4500)}
function go(hash){if(location.hash===hash)render();else location.hash=hash}
const button=(text,action,ghost=false,disabled=false)=>`<button class="btn${ghost?' ghost':''}" data-action="${action}" ${disabled?'disabled':''}>${text}${icon('arrow')}</button>`
function karateBelt(i){const id=`obi-${i}`;return `<svg class="karate-belt" viewBox="0 0 160 116" aria-hidden="true"><defs><linearGradient id="${id}-cloth" x2="0.2" y2="1"><stop stop-color="#fff" stop-opacity=".38"/><stop offset=".22" stop-color="#fff" stop-opacity=".08"/><stop offset=".48" stop-color="#000" stop-opacity=".18"/><stop offset=".72" stop-color="#fff" stop-opacity=".16"/><stop offset="1" stop-color="#000" stop-opacity=".5"/></linearGradient><pattern id="${id}-weave" width="3" height="3" patternUnits="userSpaceOnUse"><path d="M0 .5H3" stroke="#fff" stroke-opacity=".17" stroke-width=".5"/><path d="M.5 0V3" stroke="#000" stroke-opacity=".23" stroke-width=".6"/></pattern><filter id="${id}-shadow" x="-30%" y="-30%" width="160%" height="180%"><feDropShadow dx="0" dy="4" stdDeviation="3" flood-opacity=".65"/></filter></defs><g filter="url(#${id}-shadow)" fill="${colors[i]}">
${['M12 28 Q77 13 148 28 L147 48 Q81 37 13 49Z','M70 38 Q59 65 35 93 L57 107 Q80 76 86 48Z','M84 38 Q96 62 128 82 L113 101 Q84 80 72 51Z','M65 27 Q80 22 94 29 L91 53 Q78 58 65 49 Q70 38 65 27Z'].map(d=>`<g><path d="${d}"/><path d="${d}" fill="url(#${id}-cloth)"/><path d="${d}" fill="url(#${id}-weave)"/><path d="${d}" fill="none" stroke="#fff" stroke-opacity=".16" stroke-width=".7"/></g>`).join('')}
<g fill="none" stroke="#fff" stroke-opacity=".3" stroke-width=".7" stroke-dasharray="1.4 1.6"><path d="M16 32 Q78 18 144 32M16 44 Q78 32 144 43M70 55Q58 79 42 93M77 61Q67 86 56 101M91 56Q106 77 122 84M87 66Q98 83 113 94M70 29Q77 38 70 49M88 30L86 50"/></g><path d="M69 30Q78 39 91 31M70 49Q80 41 89 50" fill="none" stroke="#000" stroke-opacity=".28" stroke-width="2"/><path d="m111 83 9 7-4 5-9-7Z" fill="#161b18"/><path d="m110 87 5 4" stroke="#d9ba74" stroke-width="1"/></g></svg>`}
function beltTrack(){return `<div class="path-strip"><div><span class="eyebrow">TU CAMINO EMPIEZA AQUÍ</span><p>Un cinturón a la vez.</p></div><div class="belt-track">${bank.dojos.map((d,i)=>`<button class="belt-node ${i===state.belt?'current':''}" style="--belt:${colors[i]}" data-action="path" aria-label="Ver cinturón ${labels[i]}" ${i===state.belt?'aria-current="step"':''}><span class="belt-icon">${karateBelt(i)}</span>${labels[i]}</button>`).join('')}</div></div>`}
function home(){const d=current(),p=progress(d);return `<section class="hero"><video class="hero-media" poster="/assets/sensei-poster.jpg" src="/assets/sensei.mp4" muted playsinline preload="auto" aria-label="Sensei en el dojo tecnológico"></video><button class="pause-video" data-action="toggle-video">Reproducir ambiente ▷</button><div class="hero-copy"><span class="eyebrow">TU VIDA DIGITAL, EN BUENAS MANOS</span><h1 class="new-headline"><small>APRENDE GRATIS A</small>DEFENDERTE<small>DE LOS</small><em>CIBERATAQUES</em></h1><p>Aprende a reconocer engaños y a cuidar lo que más importa. Sin palabras difíciles. A tu ritmo.</p><div class="hero-actions">${button(p.answers.length?'Continuar mi entrenamiento':'Entrar a mi dojo','train')}<button class="text-btn" data-action="welcome"><span class="play-ring">▶</span>Conoce a tu sensei</button></div><div class="hero-note">${icon('shield')}No necesitas saber de informática para empezar.</div></div><div class="sensei-caption"><strong>Primero, respira.</strong>DESPUÉS, VERIFICA.</div></section>
<div class="content">${beltTrack()}<a class="demo-doggo" href="/personajes/doggoteka" target="_parent"><img src="/assets/doggoteka.webp" alt="DoggoTeka, mascota del dojo"><div><span class="eyebrow">TU COMPAÑERO ESPECIAL</span><h2>DoggoTeka</h2><p>¡Pausa, revisa y sigue con confianza!</p><span>Conocer mi ficha ↗</span></div></a><div class="section-head"><div><span class="eyebrow">PEQUEÑOS PASOS. GRANDES DEFENSAS.</span><h2>Hoy entrenas para la vida real.</h2></div><a href="#camino">Explorar los dojos ↗</a></div><div class="feature-grid"><article class="training-card"><img src="/assets/${state.mentor==='doggoteka'?'doggoteka.webp':state.mentor+'.jpg'}" alt="${mentorNames[state.mentor]}, tu guía" loading="lazy"><div><span class="chip">CINTURÓN ${labels[state.belt].toUpperCase()}</span><h3>${esc(d.title)}</h3><p>Mensajes, cuentas y decisiones cotidianas.<br>Una pregunta. Una nueva defensa.</p><div class="progress"><span style="width:${p.answers.length/30*100}%"></span></div><p>${p.answers.length} de 30 preguntas · Sin límite de tiempo</p><button class="text-btn" data-action="train">${p.answers.length?'Retomar donde me quedé':'Comenzar mi primera pregunta'} ${icon('arrow')}</button></div></article><article class="kata-teaser"><span class="eyebrow">TU PRÓXIMO DESAFÍO</span><h3>Del aprendizaje a la acción.</h3><p class="quiet">Cinco casos para poner a prueba tu criterio.<br>Se abre al completar las 30 preguntas.</p><button class="text-btn" data-action="${p.answers.length===30?'exam':'kata-preview'}">${p.answers.length===30?'Presentar mi kata':'Conocer el kata'} ${icon('arrow')}</button></article></div><div class="bottom-note"><div class="note-item">${icon('book')}<div><strong>Aprendes con cada respuesta</strong><p>Te explicamos el porqué, aciertes o no.</p></div></div><div class="note-item">${icon('clock')}<div><strong>Tu tiempo, tus pasos</strong><p>Sal y vuelve a tu última pregunta.</p></div></div><div class="note-item">${icon('shield')}<div><strong>Un lugar seguro para practicar</strong><p>Esta propuesta guarda el avance solo aquí.</p></div></div></div>`}
function pathView(){return `<div class="content"><div class="page-heading"><span class="eyebrow">SIETE CINTURONES · UNA VIDA MÁS SEGURA</span><h1>Tu camino en el dojo.</h1><p>Cada nivel prepara el siguiente. Responde 30 preguntas, lee las explicaciones y demuestra lo aprendido en tu kata.</p></div><div class="dojos-grid">${bank.dojos.map((d,i)=>{const p=progress(d);return `<article class="dojo-card" style="--belt:${colors[i]}"><span class="number">0${i+1} <small style="font:12px 'Trebuchet MS'">/ ${labels[i]}</small></span><h2>${esc(d.title)}</h2><p>${i>state.belt?'Se abre al aprobar el cinturón anterior.':`${p.answers.length} de 30 preguntas respondidas.`}</p><div class="progress"><span style="width:${p.answers.length/30*100}%"></span></div>${button(i>state.belt?'Aún por descubrir':p.answers.length?'Continuar entrenamiento':'Entrar al dojo','dojo:'+d.id,false,i>state.belt)}</article>`}).join('')}</div></div>`}
function terms(q){return `<details><summary>¿Una palabra nueva? Te la explicamos.</summary><dl>${Object.entries(q.terms).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></details>`}
function feedback(q,selected){return `<div class="feedback" role="status"><strong>${selected===q.correct?'Bien hecho. Estás construyendo tu defensa.':'Vamos paso a paso. Aquí puedes equivocarte sin riesgo.'}</strong><p>${esc(q.explanation)}</p></div>`}
function aside(){return `<aside class="lesson-aside"><div class="mentor-portrait"><img src="/assets/${state.mentor==='doggoteka'?'doggoteka.webp':state.mentor+'.jpg'}" alt="Tu guía ${mentorNames[state.mentor]}"></div><span class="eyebrow">${mentorNames[state.mentor]}</span><blockquote>«Tu mejor defensa es darte un momento para pensar.»</blockquote><p>No tienes que saberlo todo. Cada respuesta te ayuda a aprender algo nuevo.</p><hr><p>${icon('shield')} Tus respuestas se guardan en este navegador. Puedes salir y volver con calma.</p></aside>`}
function questionView(d){if(d.rank>state.belt){go('#camino');return ''}const p=progress(d),q=items[d.question_ids[p.cursor]],selected=p.answers[p.cursor],answered=selected!==undefined;return `<div class="content"><button class="back" data-action="home">← Volver a mi dojo</button><div class="lesson-shell"><section class="lesson-main"><div class="lesson-top"><span>CINTURÓN ${labels[d.rank].toUpperCase()}</span><span>${p.answers.length}/30 respuestas guardadas</span></div><div class="progress"><span style="width:${p.answers.length/30*100}%"></span></div><span class="eyebrow">PREGUNTA ${p.cursor+1} DE 30 · A TU RITMO</span><h1>${esc(q.prompt)}</h1>${terms(q)}<div class="answer-list">${q.options.map((o,i)=>`<button class="answer ${answered?(i===q.correct?'correct':i===selected?'wrong':''):''}" data-action="answer:${d.id}:${i}" ${answered?'disabled':''}><b>${'ABCD'[i]}</b><span>${esc(o)}${answered&&i===q.correct?'<small>RESPUESTA RECOMENDADA</small>':''}${answered&&i===selected?'<small>TU ELECCIÓN</small>':''}</span></button>`).join('')}</div>${answered?feedback(q,selected):'<p class="quiet" style="color:#596448">Lee con calma. Elige lo que harías en esta situación.</p>'}${answered?button(p.cursor===29?'Terminé mi entrenamiento':'Ya leí la explicación · Continuar','next:'+d.id):''}${p.cursor>0?`<button class="back" data-action="previous:${d.id}">← Repasar la pregunta anterior</button>`:''}</section>${aside()}</div></div>`}
function guides(){return `<div class="content"><div class="page-heading"><span class="eyebrow">NADIE APRENDE SOLO</span><h1>Encuentra a tu guía.</h1><p>Elige quién te acompañará. Todos comparten la misma enseñanza: protegerte con calma, criterio y confianza.</p></div><div class="guides">${[['doggoteka','DoggoTeka','Nuestra mascota y tu compañero especial: pausa, revisa y sigue con confianza.'],['sensei','Sensei Ren','La calma antes de actuar. Un guía para construir hábitos, paso a paso.'],['kira','Kira','La observación es su fortaleza. Te acompaña a reconocer señales de engaño.'],['aria','Aria','La confianza se practica. Cada pequeño aprendizaje es una nueva defensa.']].map(([id,name,desc])=>`<article class="guide"><img src="/assets/${id==='doggoteka'?'doggoteka.webp':id+'.jpg'}" alt="${name}" loading="lazy"><h2>${name}</h2><p>${desc}</p>${button(state.mentor===id?'Mi guía actual':'Elegir a '+name,'mentor:'+id,state.mentor!==id)}</article>`).join('')}</div></div>`}
function startExam(d){if(progress(d).answers.length<30){toast('Primero responde las 30 preguntas de este dojo.');go('#camino');return}if(!state.exams[d.id]){const used=new Set(),ids=[];for(const level of [1,1,2,2,3]){const pool=bank.items.filter(q=>q.kind==='case'&&q.belt===d.belt&&q.sublevel===level&&!used.has(q.family));const q=pool[Math.floor(Math.random()*pool.length)];ids.push(q.id);used.add(q.family)}state.exams[d.id]={ids,answers:[],selected:null};save()}go('#kata/'+d.id)}
function examView(d){if(progress(d).answers.length<30){toast('El kata se abre al completar las 30 preguntas.');go('#camino');return ''}const e=state.exams[d.id];if(!e){startExam(d);return ''}if(e.answers.length===5)return resultView(d,e);const q=items[e.ids[e.answers.length]];return `<div class="content"><button class="back" data-action="home">← Volver a mi dojo</button><div class="lesson-shell"><section class="lesson-main"><div class="lesson-top"><span>KATA · CINTURÓN ${labels[d.rank].toUpperCase()}</span><span>CASO ${e.answers.length+1}/5</span></div><div class="progress"><span style="width:${e.answers.length*20}%"></span></div><span class="eyebrow">${e.answers.length===4?'DESAFÍO FINAL · COMBINA LO APRENDIDO':'PON EN PRÁCTICA TU CRITERIO'}</span><h1>${esc(q.prompt).replace(/\n/g,'<br>')}</h1>${terms(q)}<div class="answer-list">${q.options.map((o,i)=>`<button class="answer ${e.selected===i?'chosen':''}" aria-pressed="${e.selected===i}" data-action="choose:${d.id}:${i}"><b>${'ABCD'[i]}</b><span>${esc(o)}</span></button>`).join('')}</div>${button(e.answers.length===4?'Enviar y ver resultado':'Confirmar y continuar','submit:'+d.id,false,e.selected===null)}<p style="font-size:12px;margin-top:20px">Necesitas 4 de 5 aciertos para aprobar. Al terminar verás todas las explicaciones. Este ensayo no modifica tu cuenta en línea.</p></section>${aside()}</div></div>`}
function resultView(d,e){const score=e.answers.reduce((n,a,i)=>n+(a===items[e.ids[i]].correct?1:0),0),passed=score>=4;return `<div class="content"><div class="result-wrap"><div class="page-heading"><span class="eyebrow">KATA COMPLETADO · RESULTADO LOCAL</span><h1>${passed?'La práctica da frutos.':'Cada intento te enseña.'}</h1><p>${passed?'Has dado otro paso para cuidar tu vida digital.':'Revisa las explicaciones. Puedes volver a practicar cuando te sientas listo.'}</p></div><div class="score">${score}<span style="font-size:35px;color:var(--muted)"> / 5 aciertos</span></div><p>${score*20}% · Se aprueba con al menos 75% (4 de 5).</p><div class="result-actions">${passed?button('Celebrar mi aprendizaje','celebrate'):button('Intentar otro kata','retry:'+d.id)}${button('Volver a mi dojo','home',true)}</div><h2 style="font-size:30px;margin:35px 0">Lo que te llevas de este kata.</h2>${e.ids.map((id,i)=>{const q=items[id];return `<article class="review"><span class="eyebrow">CASO ${i+1}</span><h3>${esc(q.prompt)}</h3><p>Elegiste: ${esc(q.options[e.answers[i]])}</p><p>Respuesta recomendada: ${esc(q.options[q.correct])}</p>${feedback(q,e.answers[i])}</article>`}).join('')}</div></div>`}
function modal(type){document.querySelector('#cinema-body').innerHTML=type==='welcome'?`<video src="/assets/sensei.mp4" controls muted playsinline autoplay></video><div class="dialog-copy"><span class="eyebrow">BIENVENIDO A TU DOJO</span><h2>Aquí, aprender es protegerte.</h2><p>Tu sensei te acompaña. Empieza con una pregunta y descubre una decisión que puedes usar hoy.</p>${button('Vamos a practicar','close-train')}</div>`:type==='celebrate'?`<img class="reward-art cinematic-art" src="/assets/duel.jpg" alt="Arte de Kira enfrentando una amenaza digital"><div class="dialog-copy"><span class="eyebrow">TU CONOCIMIENTO ES TU DEFENSA</span><h2>Un paso más. Más confianza.</h2><p>Celebra lo aprendido y llévalo a tu vida diaria. Esta escena usa el arte de tus referencias como presentación animada.</p>${button('Continuar mi camino','close-path')}</div>`:`<img class="reward-art" src="/assets/duel.jpg" alt="Kira en una escena de entrenamiento"><div class="dialog-copy"><span class="eyebrow">EL KATA · TU PRUEBA DE APRENDIZAJE</span><h2>Cinco decisiones. Una nueva defensa.</h2><p>Después de responder 30 preguntas, afrontarás cinco casos. El último será más desafiante. Necesitas cuatro aciertos; tendrás tiempo para pensar y explicaciones para aprender.</p>${button('Volver a entrenar','close-train')}${button('Ver propuesta de celebración','celebrate',true)}</div>`;if(!dialog.open)dialog.showModal()}
function closeDialog(){dialog.querySelector('video')?.pause();dialog.close()}
document.querySelector('.close').onclick=closeDialog
dialog.addEventListener('close',()=>dialog.querySelector('video')?.pause())
dialog.addEventListener('click',e=>{if(e.target===dialog)closeDialog()})
document.addEventListener('click',event=>{const target=event.target.closest('[data-action]');if(!target||target.disabled)return;const [action,id,num]=target.dataset.action.split(':');const d=id?bank.dojos.find(d=>d.id===id):current();switch(action){
case'home':go('#inicio');break;case'path':go('#camino');break;case'train':go('#dojo/'+current().id);break;case'dojo':go('#dojo/'+id);break;
case'answer':{const p=progress(d);if(p.answers[p.cursor]!==undefined)return;p.answers.push(Number(num));save();render(false);document.querySelector('.feedback')?.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});break}
case'next':{const p=progress(d);if(p.answers[p.cursor]===undefined)return;if(p.cursor<29){p.cursor++;save();render()}else startExam(d);break}
case'previous':{progress(d).cursor=Math.max(0,progress(d).cursor-1);save();render();break}
case'exam':startExam(current());break;case'choose':state.exams[id].selected=Number(num);save();render(false);break;
case'submit':{const e=state.exams[id];if(e.selected===null||e.answers.length>=5)return;e.answers.push(e.selected);e.selected=null;if(e.answers.length===5&&e.answers.filter((a,i)=>a===items[e.ids[i]].correct).length>=4)state.belt=Math.max(state.belt,Math.min(6,d.rank+1));save();render();break}
case'retry':delete state.exams[id];save();startExam(d);break;case'mentor':state.mentor=id;save();render(false);toast(mentorNames[id]+' te acompañará en tu entrenamiento.');break;
case'welcome':modal('welcome');break;case'kata-preview':modal('kata-preview');break;case'celebrate':modal('celebrate');break;
case'close-train':closeDialog();go('#dojo/'+current().id);break;case'close-path':closeDialog();go('#camino');break;
case'toggle-video':{const v=document.querySelector('.hero-media');if(v.paused)v.play().then(()=>target.textContent='Pausar ambiente Ⅱ').catch(()=>toast('Usa «Conoce a tu sensei» para reproducir el video.'));else{v.pause();target.textContent='Reproducir ambiente ▷'}break}
}})
function render(scroll=true){if(!bank)return;document.querySelectorAll('main video').forEach(v=>v.pause());const route=(location.hash||'#inicio').slice(1).split('/');let html;const d=bank.dojos.find(d=>d.id===route[1]);if(route[0]==='camino')html=pathView();else if(route[0]==='guias')html=guides();else if(route[0]==='dojo'&&d)html=questionView(d);else if(route[0]==='kata'&&d)html=examView(d);else html=home();main.innerHTML=html;main.className=scroll?'view-enter':'';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+route[0]));if(scroll)window.scrollTo(0,0);const v=document.querySelector('.hero-media');if(v){v.addEventListener('ended',()=>{document.querySelector('.pause-video').textContent='Reproducir ambiente ▷'});if(!matchMedia('(prefers-reduced-motion: reduce)').matches)v.play().then(()=>{const b=document.querySelector('.pause-video');if(b)b.textContent='Pausar ambiente Ⅱ'}).catch(()=>{})}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)document.querySelectorAll('video').forEach(v=>v.pause())})
window.addEventListener('hashchange',()=>render())
fetch('/bank.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{bank=data;items=Object.fromEntries(bank.items.map(q=>[q.id,q]));render()}).catch(()=>{main.innerHTML='<div class="content page-heading"><h1>No pudimos cargar el dojo.</h1><p>Recarga la página para volver a intentar.</p></div>'})
