-- Fixes 138 exam-case/question distractor options where two unrelated sentences were
-- concatenated by the content-generation process into a single answer choice.
-- Each statement keeps only the first (scenario-specific) sentence, matching the
-- already-corrected source file in 'Banco de preguntas/optimizado/'.

UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Compartir el código de desbloqueo para que alguien quite los avisos por ti."'::jsonb) WHERE id = 'C3-0010';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Tapar solo tu cara y dejar visibles los números del documento."'::jsonb) WHERE id = 'C3-0013';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Subirlo a una historia suponiendo que desaparecerá sin dejar copias."'::jsonb) WHERE id = 'C3-0013';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Guardar el número nuevo y borrar el anterior antes de comprobar."'::jsonb) WHERE id = 'C3-0015';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Una historia temporal impide que se hagan capturas."'::jsonb) WHERE id = 'P3-0013';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Los números de un documento son públicos por el hecho de tenerlo."'::jsonb) WHERE id = 'P3-0013';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Un comprobante con tu nombre garantiza que recibiste el dinero."'::jsonb) WHERE id = 'P3-0016';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Si la página vibra o emite sonidos, el problema queda confirmado."'::jsonb) WHERE id = 'P3-0018';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Solo las personas sin estudios pueden ser engañadas."'::jsonb) WHERE id = 'P3-0020';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Tapar solo tu cara y dejar visibles los números del documento."'::jsonb) WHERE id = 'P3-0033';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Reprocharle que una persona cuidadosa nunca se equivoca."'::jsonb) WHERE id = 'P3-0040';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Preguntar al mismo remitente si garantiza el premio."'::jsonb) WHERE id = 'C3-0021';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Enviar la imagen a un grupo familiar para tener más copias."'::jsonb) WHERE id = 'C3-0028';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Compartir el código de desbloqueo para que alguien quite los avisos por ti."'::jsonb) WHERE id = 'C3-0030';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Aceptar la captura porque incluye el logo del banco."'::jsonb) WHERE id = 'C3-0036';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Entregar si el comprador te deja ver la imagen en su celular."'::jsonb) WHERE id = 'C3-0036';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Reprocharle que una persona cuidadosa nunca se equivoca."'::jsonb) WHERE id = 'C3-0040';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Aceptar la captura porque incluye el logo del banco."'::jsonb) WHERE id = 'P3-0056';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Llamar al número de la alerta para que limpien el equipo."'::jsonb) WHERE id = 'P3-0058';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Enviar la imagen a un grupo familiar para tener más copias."'::jsonb) WHERE id = 'P3-0068';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Guardar el número nuevo y borrar el anterior antes de comprobar."'::jsonb) WHERE id = 'P3-0075';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Llamar al número de la alerta para que limpien el equipo."'::jsonb) WHERE id = 'P3-0078';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Pedirle que borre todo para que nadie se entere."'::jsonb) WHERE id = 'P3-0080';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Reprocharle que una persona cuidadosa nunca se equivoca."'::jsonb) WHERE id = 'P3-0080';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Compartir el código de desbloqueo para que alguien quite los avisos por ti."'::jsonb) WHERE id = 'C3-0050';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Usar los datos de un familiar si no quieres dar los tuyos."'::jsonb) WHERE id = 'C3-0052';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Subirlo a una historia suponiendo que desaparecerá sin dejar copias."'::jsonb) WHERE id = 'C3-0053';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Guardar el número nuevo y borrar el anterior antes de comprobar."'::jsonb) WHERE id = 'C3-0055';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Aceptar la captura porque incluye el logo del banco."'::jsonb) WHERE id = 'C3-0056';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Llamar al número de la alerta para que limpien el equipo."'::jsonb) WHERE id = 'C3-0058';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Pedirle que borre todo para que nadie se entere."'::jsonb) WHERE id = 'C3-0060';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Preguntar al mismo remitente si garantiza el premio."'::jsonb) WHERE id = 'P3-0081';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Enviar la imagen a un grupo familiar para tener más copias."'::jsonb) WHERE id = 'P3-0088';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Compartir el código de desbloqueo para que alguien quite los avisos por ti."'::jsonb) WHERE id = 'P3-0090';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Subirlo a una historia suponiendo que desaparecerá sin dejar copias."'::jsonb) WHERE id = 'P3-0093';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Entregar si el comprador te deja ver la imagen en su celular."'::jsonb) WHERE id = 'P3-0096';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Llamar al número de la alerta para que limpien el equipo."'::jsonb) WHERE id = 'P3-0098';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Pedirle que borre todo para que nadie se entere."'::jsonb) WHERE id = 'P3-0100';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Reprocharle que una persona cuidadosa nunca se equivoca."'::jsonb) WHERE id = 'P3-0100';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Un código mostrado en una notificación no sirve para iniciar sesión."'::jsonb) WHERE id = 'P3-0130';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Los datos de un familiar son una alternativa segura sin consultarle."'::jsonb) WHERE id = 'P3-0132';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Los números de un documento son públicos por el hecho de tenerlo."'::jsonb) WHERE id = 'P3-0133';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Un comprobante con tu nombre garantiza que recibiste el dinero."'::jsonb) WHERE id = 'P3-0136';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Solo las personas sin estudios pueden ser engañadas."'::jsonb) WHERE id = 'P3-0140';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Borrarlos sin preparar otra forma de recuperar la cuenta."'::jsonb) WHERE id = 'C3-0067';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Enviar el dinero porque la cuenta receptora fue dictada por un asesor."'::jsonb) WHERE id = 'C3-0071';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Devolver a la cuenta nueva usando como prueba su captura."'::jsonb) WHERE id = 'C3-0074';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Borrar luego la aplicación suponiendo que eso cancela todos los pagos."'::jsonb) WHERE id = 'C3-0076';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Los códigos de recuperación son seguros aunque se publiquen."'::jsonb) WHERE id = 'P3-0147';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Entregar efectivo a un mensajero evita cualquier fraude bancario."'::jsonb) WHERE id = 'P3-0151';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Desinstalar una aplicación cancela siempre su suscripción."'::jsonb) WHERE id = 'P3-0156';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Borrarlos sin preparar otra forma de recuperar la cuenta."'::jsonb) WHERE id = 'P3-0167';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Enviar el dinero porque la cuenta receptora fue dictada por un asesor."'::jsonb) WHERE id = 'P3-0171';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Devolver a la cuenta nueva usando como prueba su captura."'::jsonb) WHERE id = 'P3-0174';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Borrar luego la aplicación suponiendo que eso cancela todos los pagos."'::jsonb) WHERE id = 'P3-0176';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Desactivar todos los avisos porque cualquiera podría ser una estafa."'::jsonb) WHERE id = 'C3-0089';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Borrar luego la aplicación suponiendo que eso cancela todos los pagos."'::jsonb) WHERE id = 'C3-0096';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Cerrar solo la pestaña y dejar la sesión abierta."'::jsonb) WHERE id = 'C3-0097';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Enviar el dinero porque la cuenta receptora fue dictada por un asesor."'::jsonb) WHERE id = 'P3-0191';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Devolver a la cuenta nueva usando como prueba su captura."'::jsonb) WHERE id = 'P3-0214';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Desactivar todos los avisos porque cualquiera podría ser una estafa."'::jsonb) WHERE id = 'C3-0109';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Enviar el dinero porque la cuenta receptora fue dictada por un asesor."'::jsonb) WHERE id = 'C3-0111';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Aprobar las operaciones que señale el asesor para terminar rápido."'::jsonb) WHERE id = 'C3-0118';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Desactivar todos los avisos porque cualquiera podría ser una estafa."'::jsonb) WHERE id = 'P3-0229';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Borrar luego la aplicación suponiendo que eso cancela todos los pagos."'::jsonb) WHERE id = 'P3-0236';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Todo dinero que llega por error puede gastarse sin revisar su origen."'::jsonb) WHERE id = 'P3-0274';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Dar acceso total porque imprimir una factura requiere todas las fotos."'::jsonb) WHERE id = 'C3-0126';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Dejar al supuesto técnico operar mientras sales a trabajar."'::jsonb) WHERE id = 'C3-0127';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Abrirlo porque el nombre incluye «pdf»."'::jsonb) WHERE id = 'C3-0128';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Poner el teléfono en silencio impide a cualquier aplicación usar el micrófono."'::jsonb) WHERE id = 'P3-0284';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Un anuncio puede identificar la causa exacta solo porque viste su mensaje."'::jsonb) WHERE id = 'P3-0292';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Comprar el limpiador del anuncio para resolver el supuesto espionaje."'::jsonb) WHERE id = 'P3-0312';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Aceptar pensando que apagar el volumen impide grabar."'::jsonb) WHERE id = 'C3-0144';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Aceptar pensando que apagar el volumen impide grabar."'::jsonb) WHERE id = 'P3-0324';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Dar acceso total porque imprimir una factura requiere todas las fotos."'::jsonb) WHERE id = 'P3-0346';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Aceptar pensando que apagar el volumen impide grabar."'::jsonb) WHERE id = 'C3-0164';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Comprar el limpiador del anuncio para resolver el supuesto espionaje."'::jsonb) WHERE id = 'C3-0172';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Aceptar pensando que apagar el volumen impide grabar."'::jsonb) WHERE id = 'P3-0364';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Dar acceso total porque imprimir una factura requiere todas las fotos."'::jsonb) WHERE id = 'P3-0366';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Comprar el limpiador del anuncio para resolver el supuesto espionaje."'::jsonb) WHERE id = 'P3-0372';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"El nombre conocido de una herramienta certifica a toda persona que la use."'::jsonb) WHERE id = 'P3-0407';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Desactivar la protección permite comprobar archivos sin riesgo."'::jsonb) WHERE id = 'P3-0408';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Borrar solo los iconos de las aplicaciones bancarias."'::jsonb) WHERE id = 'C3-0139';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Introducir la clave porque el código estaba dentro del restaurante."'::jsonb) WHERE id = 'C3-0183';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Pedir al mismo asistente que prometa que no se equivoca como única verificación."'::jsonb) WHERE id = 'C3-0200';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Borrar solo los iconos de las aplicaciones bancarias."'::jsonb) WHERE id = 'P3-0319';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Todo código colocado dentro de un negocio fue revisado por el dueño."'::jsonb) WHERE id = 'P3-0423';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Todos los asistentes eliminan inmediatamente todo lo que reciben."'::jsonb) WHERE id = 'P3-0439';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Introducir la clave porque el código estaba dentro del restaurante."'::jsonb) WHERE id = 'P3-0443';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Usar la clave de otra cuenta para poder leer el menú."'::jsonb) WHERE id = 'P3-0443';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Pedir al mismo asistente que prometa que no se equivoca como única verificación."'::jsonb) WHERE id = 'P3-0460';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Introducir la clave porque el código estaba dentro del restaurante."'::jsonb) WHERE id = 'C3-0203';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Borrar solo los iconos de las aplicaciones bancarias."'::jsonb) WHERE id = 'P3-0359';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Introducir la clave porque el código estaba dentro del restaurante."'::jsonb) WHERE id = 'P3-0463';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Compartir también las contraseñas para que el asistente compruebe las cuentas."'::jsonb) WHERE id = 'P3-0479';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Borrar solo los iconos de las aplicaciones bancarias."'::jsonb) WHERE id = 'C3-0179';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Introducir la clave porque el código estaba dentro del restaurante."'::jsonb) WHERE id = 'P3-0503';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Compartir también las contraseñas para que el asistente compruebe las cuentas."'::jsonb) WHERE id = 'P3-0519';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Todo código colocado dentro de un negocio fue revisado por el dueño."'::jsonb) WHERE id = 'P3-0543';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Pagar porque el correo está dentro del hilo de siempre."'::jsonb) WHERE id = 'C3-0192';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"La presencia de una persona famosa garantiza la recuperación del dinero."'::jsonb) WHERE id = 'P3-0422';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Un logotipo en el perfil verifica que el soporte es oficial."'::jsonb) WHERE id = 'P3-0425';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Una foto o una videollamada garantiza que toda historia posterior sea verdadera."'::jsonb) WHERE id = 'P3-0430';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Usar solo el enlace del video para comprobar la inversión."'::jsonb) WHERE id = 'P3-0442';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Invertir porque el rostro y los labios se ven naturales."'::jsonb) WHERE id = 'P3-0442';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Entrar porque la cuenta y la foto son las de siempre."'::jsonb) WHERE id = 'P3-0454';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Enviar la foto de tu tarjeta para que cobren el aporte."'::jsonb) WHERE id = 'P3-0455';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Enviar la foto de tu tarjeta para que cobren el aporte."'::jsonb) WHERE id = 'C3-0215';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Usar solo el enlace del video para comprobar la inversión."'::jsonb) WHERE id = 'P3-0462';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Invertir porque el rostro y los labios se ven naturales."'::jsonb) WHERE id = 'P3-0462';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Pagar porque el correo está dentro del hilo de siempre."'::jsonb) WHERE id = 'P3-0472';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Invertir porque el rostro y los labios se ven naturales."'::jsonb) WHERE id = 'P3-0482';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Pedir un préstamo para resolver la emergencia de inmediato."'::jsonb) WHERE id = 'P3-0490';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Entrar porque la cuenta y la foto son las de siempre."'::jsonb) WHERE id = 'P3-0494';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Enviar la foto de tu tarjeta para que cobren el aporte."'::jsonb) WHERE id = 'P3-0495';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Confiar porque respondió inmediatamente a tu comentario."'::jsonb) WHERE id = 'C3-0225';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Pedir un préstamo para resolver la emergencia de inmediato."'::jsonb) WHERE id = 'C3-0230';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Enviar la foto de tu tarjeta para que cobren el aporte."'::jsonb) WHERE id = 'C3-0235';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Pedir un préstamo para resolver la emergencia de inmediato."'::jsonb) WHERE id = 'P3-0510';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Pagar porque el correo está dentro del hilo de siempre."'::jsonb) WHERE id = 'P3-0512';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Enviar la foto de tu tarjeta para que cobren el aporte."'::jsonb) WHERE id = 'P3-0515';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"La presencia de una persona famosa garantiza la recuperación del dinero."'::jsonb) WHERE id = 'P3-0542';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Los comentarios positivos certifican una inversión."'::jsonb) WHERE id = 'P3-0542';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Un concurso necesita la contraseña de otra cuenta para contar un voto."'::jsonb) WHERE id = 'P3-0554';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Escribir a la dirección desconocida enviando más facturas para pedir explicaciones."'::jsonb) WHERE id = 'C3-0243';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"La recuperación no afecta quién puede controlar la cuenta."'::jsonb) WHERE id = 'P3-0565';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Escribir a la dirección desconocida enviando más facturas para pedir explicaciones."'::jsonb) WHERE id = 'P3-0583';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Esperar porque el cambio no importa mientras la contraseña siga funcionando."'::jsonb) WHERE id = 'P3-0585';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Escribir a la dirección desconocida enviando más facturas para pedir explicaciones."'::jsonb) WHERE id = 'C3-0263';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Llamar al teléfono nuevo para pedir permiso de usar la cuenta."'::jsonb) WHERE id = 'C3-0265';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Escribir a la dirección desconocida enviando más facturas para pedir explicaciones."'::jsonb) WHERE id = 'P3-0603';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,3}', '"Llamar al teléfono nuevo para pedir permiso de usar la cuenta."'::jsonb) WHERE id = 'P3-0605';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,1}', '"Escribir a la dirección desconocida enviando más facturas para pedir explicaciones."'::jsonb) WHERE id = 'P3-0623';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Llamar al teléfono nuevo para pedir permiso de usar la cuenta."'::jsonb) WHERE id = 'P3-0625';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Llamar al teléfono nuevo para pedir permiso de usar la cuenta."'::jsonb) WHERE id = 'C3-0285';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,0}', '"Escribir a la dirección desconocida enviando más facturas para pedir explicaciones."'::jsonb) WHERE id = 'P3-0643';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"Esperar porque el cambio no importa mientras la contraseña siga funcionando."'::jsonb) WHERE id = 'P3-0645';
UPDATE public.learning_items SET content = jsonb_set(content, '{options,2}', '"La recuperación no afecta quién puede controlar la cuenta."'::jsonb) WHERE id = 'P3-0685';
