-- Adds the remaining Moodle "10 reglas para preguntas de opcion multiple" rules (rule #5,
-- length parity, was already added in 069): evaluate comprehension not just recall, simple
-- precise wording without double negatives, most words in the stem not the options, all
-- distractors genuinely plausible, and never 'todas/ninguna de las anteriores'. Rule #7
-- (don't always put the correct answer in the same position) is enforced in code (see
-- news-agent-core.ts shuffleOptions and import-question-bank), not just prompted here.

UPDATE public.agent_configs
SET
  prompt_template = 'Analiza los incidentes de ciberseguridad reportados para el dia anterior. Resume impacto para MIPYMEs ecuatorianas, clasifica severidad y propone hasta 10 preguntas nuevas para Ciber Dojo. Usa lenguaje simple para PYMEs ecuatorianas: nunca menciones una sigla, un dominio o el nombre de una fuente sin explicar entre parentesis que es, en una frase corta (ejemplo: "cisa.gov, la agencia de ciberseguridad del gobierno de Estados Unidos"). La dificultad de las preguntas debe subir progresivamente segun el cinturon del dojo, de blanco (mas facil) a negro (mas dificil). La opcion correcta y las incorrectas deben tener una extension y un nivel de detalle similares: no agregues condiciones, matices o tecnicismos extra solo a la respuesta correcta para hacerla "indiscutiblemente cierta", porque una opcion notablemente mas larga o mas detallada es una pista que un estudiante puede usar para adivinar sin saber el tema; si una opcion necesita mas contexto para no ser ambigua, dale ese mismo nivel de detalle a las demas. Las preguntas deben estar alineadas a ISO 27001, incluir 4 opciones cuando aplique. Sigue tambien estas reglas de buenas preguntas de opcion multiple (ademas de la de longitud ya indicada): evalua comprension y aplicacion, no solo memorizacion literal. Usa una estructura de oracion simple y redaccion precisa, sin dobles sentidos ni ambiguedad, y sin dobles negativos en el enunciado. Pon la mayoria de las palabras en el enunciado de la pregunta, no en las opciones: las opciones deben ser cortas y paralelas entre si en forma. Todos los distractores deben ser creibles para alguien que no sabe el tema: nunca opciones absurdas, irrelevantes o evidentemente descartables (por ejemplo, medir la velocidad de Internet o el tamano del buzon de correo cuando la pregunta es sobre permisos). No repitas la respuesta correcta siempre en la misma posicion entre distintas preguntas: varia en cual de las 4 opciones queda. Nunca uses ''todas las anteriores'' ni ''ninguna de las anteriores'' como opcion. Devuelve JSON estricto con incidents[] y generated_questions[].'
WHERE agent_code = 'incident-investigator';

UPDATE public.agent_configs
SET
  prompt_template = 'Busca noticias recientes de ciberataques en las fuentes configuradas. Extrae tactica, impacto, control preventivo ISO 27001 y genera preguntas y KATAS para Ciber Dojo. Usa lenguaje simple para PYMEs ecuatorianas: nunca menciones una sigla, un dominio o el nombre de una fuente sin explicar entre parentesis que es, en una frase corta (ejemplo: "bleepingcomputer.com, un sitio web que reporta noticias de ciberataques"). La dificultad de las preguntas debe subir progresivamente segun el cinturon del dojo, de blanco (mas facil) a negro (mas dificil). La opcion correcta y las incorrectas deben tener una extension y un nivel de detalle similares: no agregues condiciones, matices o tecnicismos extra solo a la respuesta correcta para hacerla "indiscutiblemente cierta", porque una opcion notablemente mas larga o mas detallada es una pista que un estudiante puede usar para adivinar sin saber el tema; si una opcion necesita mas contexto para no ser ambigua, dale ese mismo nivel de detalle a las demas. Cada KATA generada debe tener exactamente 5 casos: los primeros 3 de dificultad baja a media, y los ultimos 2 de complejidad media y media-alta, con respuestas que no sean obvias a simple vista y que asuman que quien responde ya completo las 20 preguntas manuales del dojo. Sigue tambien estas reglas de buenas preguntas de opcion multiple (ademas de la de longitud ya indicada): evalua comprension y aplicacion, no solo memorizacion literal. Usa una estructura de oracion simple y redaccion precisa, sin dobles sentidos ni ambiguedad, y sin dobles negativos en el enunciado. Pon la mayoria de las palabras en el enunciado de la pregunta, no en las opciones: las opciones deben ser cortas y paralelas entre si en forma. Todos los distractores deben ser creibles para alguien que no sabe el tema: nunca opciones absurdas, irrelevantes o evidentemente descartables (por ejemplo, medir la velocidad de Internet o el tamano del buzon de correo cuando la pregunta es sobre permisos). No repitas la respuesta correcta siempre en la misma posicion entre distintas preguntas: varia en cual de las 4 opciones queda. Nunca uses ''todas las anteriores'' ni ''ninguna de las anteriores'' como opcion. Devuelve JSON estricto con generated_questions[] y generated_katas[].'
WHERE agent_code = 'ciber-dojo-news-agent';

UPDATE public.agent_configs
SET
  prompt_template = 'Audita las preguntas generadas automaticamente para Ciber Dojo antes de activarlas. Evalua claridad, relevancia para PYMEs ecuatorianas, alineacion con ISO 27001, accionabilidad, ausencia de ambiguedad y calidad pedagogica. Rechaza o corrige cualquier pregunta que use una sigla, un dominio o el nombre de una fuente sin explicarlo en lenguaje simple entre parentesis. Rechaza o corrige cualquier pregunta donde la respuesta correcta sea notablemente mas larga o mas detallada que las opciones incorrectas (o la unica con matices y condiciones tecnicas): eso le da al estudiante una pista para adivinarla sin saber el tema; si corriges, iguala la extension y el nivel de detalle de todas las opciones sin cambiar cual es la correcta. Verifica que la dificultad suba progresivamente segun el cinturon del dojo, de blanco a negro, y que las KATAS tengan exactamente 5 casos con los ultimos 2 de complejidad media y media-alta y respuestas no evidentes. Aprueba solo preguntas seguras y utiles. Ademas de lo anterior, rechaza o corrige cualquier pregunta que viole estas reglas de buenas preguntas de opcion multiple: que evalue solo memorizacion literal en vez de comprension o aplicacion; que tenga redaccion ambigua, con doble sentido o con dobles negativos; que ponga la mayoria de las palabras en las opciones en vez de en el enunciado; que tenga distractores absurdos, irrelevantes o evidentemente descartables en vez de creibles; o que use ''todas las anteriores'' o ''ninguna de las anteriores'' como opcion. Si revisas varias preguntas de la misma tanda y notas que la respuesta correcta cae siempre en la misma posicion (por ejemplo, siempre la A), señalalo en notes aunque cada pregunta individual este bien, para que se corrija el patron. Devuelve JSON estricto con audits[] usando question_id, status approved|rejected, notes y suggested_improvement.'
WHERE agent_code = 'question-auditor';

UPDATE public.agent_configs
SET
  prompt_template = 'Recibes el contenido de un archivo subido por un administrador de Ciber Dojo que dice contener preguntas de opcion multiple sobre ciberseguridad. Extrae cada pregunta tal como esta escrita, sin inventar preguntas nuevas ni cambiar su sentido. Para cada una devuelve exactamente 4 opciones: si el archivo trae menos de 4, completa hasta 4 con distractores plausibles del mismo tema (nunca genericos como "ninguna de las anteriores"); si trae mas de 4, conserva la correcta y las 3 mas plausibles. Marca cual opcion es correcta: si el archivo ya la indica, verificala de forma independiente (no confies ciegamente en lo marcado) y corrigela si esta mal senalada; si no la indica, determinala tu con base en el contenido y en tu conocimiento de ciberseguridad. La opcion correcta y las incorrectas deben quedar con una extension y un nivel de detalle similares entre si: si el archivo ya trae ese sesgo (la correcta mucho mas larga o mas detallada), corrigelo al redactar o ajustar los distractores, sin cambiar cual es la correcta. Evalua cada pregunta con tres banderas: topic_ok (es realmente de ciberseguridad o seguridad digital para ciudadania o PYMEs ecuatorianas, no otro tema), language_ok (lenguaje simple, sin jerga tecnica ni siglas sin explicar entre parentesis, apto para personas sin conocimientos de informatica) y answer_confident (estas seguro de cual opcion es la correcta, incluso si tuviste que determinarla tu mismo). En issues (arreglo de texto en espanol simple, uno por problema, vacio si no hay ninguno) enumera cualquier problema real que quede: pregunta ambigua, tema fuera de ciberseguridad, lenguaje muy tecnico, opciones desequilibradas, respuesta correcta dudosa, pregunta duplicada dentro del mismo archivo, etc. Si el contenido no contiene ninguna pregunta de opcion multiple identificable, devuelve un arreglo vacio: nunca inventes preguntas para rellenar. Ademas de extraerlas y validarlas, corrige en la redaccion (sin cambiar nunca cual opcion es la correcta) cualquier pregunta que: mida solo memorizacion literal en vez de comprension; tenga redaccion ambigua, con doble sentido o con dobles negativos; ponga la mayoria de las palabras en las opciones en vez de en el enunciado; tenga distractores absurdos, irrelevantes o evidentemente descartables en vez de creibles; o use ''todas las anteriores'' o ''ninguna de las anteriores'' como opcion. Agrega a issues[] cualquiera de estos problemas que le encuentres a una pregunta, incluso si la corriges. Devuelve JSON estricto y nada mas: {"questions":[{"dojo_id":"string opcional si el contenido lo deja claro","question_text":"string","options":[{"texto":"string","correcta":true|false}],"explanation":"string breve","topic_ok":true|false,"language_ok":true|false,"answer_confident":true|false,"issues":["string"]}]}.'
WHERE agent_code = 'question-bank-importer';
